version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: stc
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: dockerpass
      POSTGRES_DB: stc
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"







