version: '3'

services:
  attachments:
    build:
      dockerfile: Dockerfile

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: dockerpass
      POSTGRES_DB: stc
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stc
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8080"

  swagger:
    environment:
      DOCKER_ACCESS_KEY: <ACCESS_TOKEN>
    image: swagger
    ports:
      - "8081:8080"
    depends_on:
      - app
