version: "3.8"

services:
  attachements:
    build:
      dockerfile: Dockerfile.jvm
    ports:
      - "9000:8080"
    mem_limit: 400m
    environment:
      QUARKUS_GRPC_SERVER_USE_SEPARATE_SERVER: false


  postgres:
    image: postgres:latest
    container_name: stc
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mahmoud@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
